// i18n strings for: admin  (keys prefixed "admin.")
export const en: Record<string, string> = {
  // ── AdminDashboard ──
  "admin.title": "Admin Panel",
  "admin.subtitle": "InkMagnet — full visibility",
  "admin.manageUsers": "Manage users",
  "admin.loadFailed": "Failed to load admin data. Check ADMIN_EMAIL env var.",
  "admin.stat.projects": "Projects",
  "admin.stat.users": "Users",
  "admin.stat.paid": "Paid",
  "admin.stat.completed": "Completed",
  "admin.stat.revenue": "Revenue",
  "admin.stat.totalTokens": "Total Tokens",
  "admin.stat.apiCost": "API Cost",
  "admin.allProjects": "All Projects ({n})",
  "admin.col.title": "Title",
  "admin.col.user": "User",
  "admin.col.stage": "Stage",
  "admin.col.payment": "Payment",
  "admin.col.pages": "Pages",
  "admin.col.chapters": "Chapters",
  "admin.col.tokens": "Tokens",
  "admin.col.cost": "Cost",
  "admin.col.updated": "Updated",
  "admin.untitled": "Untitled",

  // ── AdminUsers ──
  "admin.users.title": "User management",
  "admin.users.count": "{n} user(s)",
  "admin.users.backToDashboard": "← Admin dashboard",
  "admin.users.searchPlaceholder": "Search email or name…",
  "admin.users.col.email": "Email",
  "admin.users.col.name": "Name",
  "admin.users.col.status": "Status",
  "admin.users.col.books": "Books",
  "admin.users.col.joined": "Joined",
  "admin.users.col.actions": "Actions",
  "admin.users.verified": "verified",
  "admin.users.unverified": "unverified",
  "admin.users.markVerified": "Mark verified",
  "admin.users.markUnverified": "Mark unverified",
  "admin.users.rename": "Rename",
  "admin.users.renamePrompt": "New name:",
  "admin.users.deleteTitle": "Delete user (and all their books)",
  "admin.users.deleteConfirm": "Delete {email} and ALL their {n} book(s)? This cannot be undone.",
  "admin.users.booksHeading": "Books ({n})",
  "admin.users.noBooks": "No books yet.",
  "admin.users.noUsers": "No users found.",

  // ── AdminProjectDetail ──
  "admin.detail.backToPanel": "Admin Panel",
  "admin.detail.notFound": "Project not found",
  "admin.detail.refreshAll": "Refresh all",
  "admin.detail.reResearch": "Re-research",
  "admin.detail.regenStructure": "Re-gen Structure",
  "admin.detail.recompilePdf": "Re-compile PDF",
  "admin.detail.regenerateAll": "Re-generate All",
  "admin.detail.delete": "Delete",
  "admin.detail.bookCompleted": "Book completed — PDF ready",
  "admin.detail.downloadPdf": "Download PDF",
  "admin.detail.confirmRegenerate": "Re-generate all chapters? This will overwrite existing content.",
  "admin.detail.confirmReResearch": "Re-run research pipeline? This will replace existing research data.",
  "admin.detail.confirmRegenStructure": "Re-generate structure? This includes running research first.",
  "admin.detail.confirmDelete": "DELETE this project permanently?\n\n\"{name}\"\n\nThis cannot be undone!",
  "admin.detail.toast.recompileStarted": "Recompilation started",
  "admin.detail.toast.regenerateStarted": "Regeneration started",
  "admin.detail.toast.reResearchStarted": "Research pipeline started",
  "admin.detail.toast.regenStructureStarted": "Structure regeneration started",
  "admin.detail.toast.projectDeleted": "Project deleted",
  "admin.detail.toast.failed": "Failed",
  "admin.detail.toast.deleteFailed": "Failed to delete",
  "admin.detail.toast.loadSourceFailed": "Failed to load source text",
  "admin.detail.toast.loadLatexFailed": "Failed to load LaTeX",
  // meta cards
  "admin.detail.meta.stage": "Stage",
  "admin.detail.meta.payment": "Payment",
  "admin.detail.meta.generation": "Generation",
  "admin.detail.meta.pages": "Pages",
  "admin.detail.meta.tokens": "Tokens",
  "admin.detail.meta.cost": "Cost",
  "admin.detail.meta.research": "Research",
  "admin.detail.meta.researchSources": "{n} sources",
  "admin.detail.meta.researchNone": "None",
  // sections
  "admin.detail.section.research": "0. Research Pipeline",
  "admin.detail.section.structure": "1. Structure Generation",
  "admin.detail.section.chapters": "2. Chapter Generation (LaTeX)",
  "admin.detail.section.rawData": "3. Raw Project Data",
  "admin.detail.noResearch": "No research data — pipeline hasn't run or API keys not configured",
  "admin.detail.promptToClaude": "Prompt → Claude",
  "admin.detail.claudeResponse": "Claude Response",
  "admin.detail.version": "Version: {n}",
  "admin.detail.userEdited": "User edited: {v}",
  "admin.detail.yes": "Yes",
  "admin.detail.no": "No",
  "admin.detail.noStructure": "No structure data yet",
  "admin.detail.noChapters": "No chapters generated yet",
  "admin.detail.rawObject": "Full project object",
  // research view
  "admin.research.searchQueries": "Search Queries",
  "admin.research.searchResults": "Search Results",
  "admin.research.scrapedOk": "Scraped OK",
  "admin.research.selected": "Selected",
  "admin.research.selectedDetail": "{n} ({native} native + {en} EN)",
  "admin.research.totalChars": "Total Chars",
  "admin.research.qualityAssessment": "Claude's Quality Assessment",
  "admin.research.googleTarget": "Google Results — Target Language ({n})",
  "admin.research.googleEnglish": "Google Results — English Supplement ({n})",
  "admin.research.noSearchResults": "No search results",
  "admin.research.scraping": "Scraping ({ok}/{total} OK)",
  "admin.research.chars": "{n} chars",
  "admin.research.failed": "failed",
  "admin.research.noScraping": "No scraping data",
  "admin.research.selectedSources": "Step 4: Selected Sources ({n})",
  "admin.research.noSources": "No sources selected",
  "admin.research.researchedAt": "Researched: {date}",
  "admin.research.charsCount": "{n} chars",
  "admin.research.showSource": "Show full source text ({n} chars)",
  "admin.research.hideSource": "Hide full source text ({n} chars)",
  // chapter block
  "admin.chapter.noPrompts": "No prompts logged",
  "admin.chapter.noResponses": "No responses logged",
  "admin.chapter.truncated": "\n\n... [truncated]",
  "admin.chapter.responseLabel": "Response — {step}",
  "admin.chapter.showLatex": "Show full LaTeX ({n} chars)",
  "admin.chapter.hideLatex": "Hide full LaTeX ({n} chars)",
  "admin.code.latexSource": "LaTeX source",
  "admin.copy": "Copy",
};

export const pl: Record<string, string> = {
  // ── AdminDashboard ──
  "admin.title": "Panel administratora",
  "admin.subtitle": "InkMagnet — pełny wgląd",
  "admin.manageUsers": "Zarządzaj użytkownikami",
  "admin.loadFailed": "Nie udało się wczytać danych admina. Sprawdź zmienną ADMIN_EMAIL.",
  "admin.stat.projects": "Projekty",
  "admin.stat.users": "Użytkownicy",
  "admin.stat.paid": "Opłacone",
  "admin.stat.completed": "Gotowe",
  "admin.stat.revenue": "Przychód",
  "admin.stat.totalTokens": "Tokeny łącznie",
  "admin.stat.apiCost": "Koszt API",
  "admin.allProjects": "Wszystkie projekty ({n})",
  "admin.col.title": "Tytuł",
  "admin.col.user": "Użytkownik",
  "admin.col.stage": "Etap",
  "admin.col.payment": "Płatność",
  "admin.col.pages": "Strony",
  "admin.col.chapters": "Rozdziały",
  "admin.col.tokens": "Tokeny",
  "admin.col.cost": "Koszt",
  "admin.col.updated": "Zaktualizowano",
  "admin.untitled": "Bez tytułu",

  // ── AdminUsers ──
  "admin.users.title": "Zarządzanie użytkownikami",
  "admin.users.count": "Użytkownicy: {n}",
  "admin.users.backToDashboard": "← Panel administratora",
  "admin.users.searchPlaceholder": "Szukaj po e-mailu lub nazwie…",
  "admin.users.col.email": "E-mail",
  "admin.users.col.name": "Nazwa",
  "admin.users.col.status": "Status",
  "admin.users.col.books": "Książki",
  "admin.users.col.joined": "Dołączył",
  "admin.users.col.actions": "Akcje",
  "admin.users.verified": "zweryfikowany",
  "admin.users.unverified": "niezweryfikowany",
  "admin.users.markVerified": "Oznacz jako zweryfikowany",
  "admin.users.markUnverified": "Oznacz jako niezweryfikowany",
  "admin.users.rename": "Zmień nazwę",
  "admin.users.renamePrompt": "Nowa nazwa:",
  "admin.users.deleteTitle": "Usuń użytkownika (i wszystkie jego książki)",
  "admin.users.deleteConfirm": "Usunąć {email} i WSZYSTKIE jego książki ({n})? Tej operacji nie można cofnąć.",
  "admin.users.booksHeading": "Książki ({n})",
  "admin.users.noBooks": "Brak książek.",
  "admin.users.noUsers": "Nie znaleziono użytkowników.",

  // ── AdminProjectDetail ──
  "admin.detail.backToPanel": "Panel administratora",
  "admin.detail.notFound": "Nie znaleziono projektu",
  "admin.detail.refreshAll": "Odśwież wszystko",
  "admin.detail.reResearch": "Ponów research",
  "admin.detail.regenStructure": "Odtwórz strukturę",
  "admin.detail.recompilePdf": "Przekompiluj PDF",
  "admin.detail.regenerateAll": "Wygeneruj wszystko ponownie",
  "admin.detail.delete": "Usuń",
  "admin.detail.bookCompleted": "Książka gotowa — PDF dostępny",
  "admin.detail.downloadPdf": "Pobierz PDF",
  "admin.detail.confirmRegenerate": "Wygenerować ponownie wszystkie rozdziały? Spowoduje to nadpisanie istniejącej treści.",
  "admin.detail.confirmReResearch": "Uruchomić ponownie pipeline researchu? Zastąpi to istniejące dane researchu.",
  "admin.detail.confirmRegenStructure": "Wygenerować strukturę ponownie? Obejmuje to najpierw uruchomienie researchu.",
  "admin.detail.confirmDelete": "USUNĄĆ ten projekt na stałe?\n\n\"{name}\"\n\nTej operacji nie można cofnąć!",
  "admin.detail.toast.recompileStarted": "Rozpoczęto przekompilowanie",
  "admin.detail.toast.regenerateStarted": "Rozpoczęto ponowne generowanie",
  "admin.detail.toast.reResearchStarted": "Uruchomiono pipeline researchu",
  "admin.detail.toast.regenStructureStarted": "Rozpoczęto ponowne generowanie struktury",
  "admin.detail.toast.projectDeleted": "Projekt usunięty",
  "admin.detail.toast.failed": "Nie powiodło się",
  "admin.detail.toast.deleteFailed": "Nie udało się usunąć",
  "admin.detail.toast.loadSourceFailed": "Nie udało się wczytać tekstu źródła",
  "admin.detail.toast.loadLatexFailed": "Nie udało się wczytać kodu LaTeX",
  // meta cards
  "admin.detail.meta.stage": "Etap",
  "admin.detail.meta.payment": "Płatność",
  "admin.detail.meta.generation": "Generowanie",
  "admin.detail.meta.pages": "Strony",
  "admin.detail.meta.tokens": "Tokeny",
  "admin.detail.meta.cost": "Koszt",
  "admin.detail.meta.research": "Research",
  "admin.detail.meta.researchSources": "źródła: {n}",
  "admin.detail.meta.researchNone": "Brak",
  // sections
  "admin.detail.section.research": "0. Pipeline researchu",
  "admin.detail.section.structure": "1. Generowanie struktury",
  "admin.detail.section.chapters": "2. Generowanie rozdziałów (LaTeX)",
  "admin.detail.section.rawData": "3. Surowe dane projektu",
  "admin.detail.noResearch": "Brak danych researchu — pipeline nie został uruchomiony lub nie skonfigurowano kluczy API",
  "admin.detail.promptToClaude": "Prompt → Claude",
  "admin.detail.claudeResponse": "Odpowiedź Claude",
  "admin.detail.version": "Wersja: {n}",
  "admin.detail.userEdited": "Edytowane przez użytkownika: {v}",
  "admin.detail.yes": "Tak",
  "admin.detail.no": "Nie",
  "admin.detail.noStructure": "Brak danych struktury",
  "admin.detail.noChapters": "Nie wygenerowano jeszcze rozdziałów",
  "admin.detail.rawObject": "Pełny obiekt projektu",
  // research view
  "admin.research.searchQueries": "Zapytania wyszukiwania",
  "admin.research.searchResults": "Wyniki wyszukiwania",
  "admin.research.scrapedOk": "Pobrano poprawnie",
  "admin.research.selected": "Wybrane",
  "admin.research.selectedDetail": "{n} ({native} natywne + {en} EN)",
  "admin.research.totalChars": "Łącznie znaków",
  "admin.research.qualityAssessment": "Ocena jakości przez Claude",
  "admin.research.googleTarget": "Wyniki Google — język docelowy ({n})",
  "admin.research.googleEnglish": "Wyniki Google — uzupełnienie angielskie ({n})",
  "admin.research.noSearchResults": "Brak wyników wyszukiwania",
  "admin.research.scraping": "Pobieranie ({ok}/{total} OK)",
  "admin.research.chars": "{n} znaków",
  "admin.research.failed": "niepowodzenie",
  "admin.research.noScraping": "Brak danych pobierania",
  "admin.research.selectedSources": "Krok 4: Wybrane źródła ({n})",
  "admin.research.noSources": "Nie wybrano źródeł",
  "admin.research.researchedAt": "Zbadano: {date}",
  "admin.research.charsCount": "{n} znaków",
  "admin.research.showSource": "Pokaż pełny tekst źródła ({n} znaków)",
  "admin.research.hideSource": "Ukryj pełny tekst źródła ({n} znaków)",
  // chapter block
  "admin.chapter.noPrompts": "Brak zapisanych promptów",
  "admin.chapter.noResponses": "Brak zapisanych odpowiedzi",
  "admin.chapter.truncated": "\n\n... [skrócono]",
  "admin.chapter.responseLabel": "Odpowiedź — {step}",
  "admin.chapter.showLatex": "Pokaż pełny LaTeX ({n} znaków)",
  "admin.chapter.hideLatex": "Ukryj pełny LaTeX ({n} znaków)",
  "admin.code.latexSource": "Źródło LaTeX",
  "admin.copy": "Kopiuj",
};
