// i18n strings for: aiEdit  (keys prefixed "aiEdit.")
// AI edit of a finished book: one instruction, a preview, accept or reject.
export const en: Record<string, string> = {
  "aiEdit.title": "Improve with AI",
  "aiEdit.text":
    "Point at a chapter or a section and say what to change: shorten, simplify, add an example, change the tone. You see the result first and decide whether to keep it.",
  "aiEdit.left": "Edits left for this book: {n} of {max}",
  "aiEdit.noneLeft": "You have used all {max} AI edits for this book. For anything else use “Check by a human” below or edit the text yourself in the editor.",
  "aiEdit.scopeChapter": "Chapter",
  "aiEdit.scopeSection": "Part of the chapter",
  "aiEdit.wholeChapter": "The whole chapter",
  "aiEdit.chapterOption": "{n}. {title}",
  "aiEdit.tooLarge": "(too long for one edit, pick a section)",
  "aiEdit.promptLabel": "What should change?",
  "aiEdit.promptPlaceholder": "e.g. Shorten this section by a third and keep the checklist. Or: explain the second paragraph in simpler words and add a short everyday example.",
  "aiEdit.start": "Show me the change",
  "aiEdit.unsaved": "Save your changes in the editor first. An AI edit works on the saved text.",
  "aiEdit.running": "Editing…",
  "aiEdit.runningText": "This usually takes one to two minutes. You can leave this page; the preview will wait here.",
  "aiEdit.previewTitle": "Preview of the change",
  "aiEdit.previewScope": "Scope: {s}",
  "aiEdit.previewPrompt": "Your instruction: {s}",
  "aiEdit.stats": "{before} → {after} words",
  "aiEdit.statsFootnotes": "footnotes: {before} → {after}",
  "aiEdit.legendRemoved": "removed",
  "aiEdit.legendAdded": "new",
  "aiEdit.showUnchanged": "Show unchanged paragraphs",
  "aiEdit.hideUnchanged": "Hide unchanged paragraphs",
  "aiEdit.unchangedCount": "{n} unchanged paragraphs",
  "aiEdit.accept": "Keep this change",
  "aiEdit.reject": "Discard",
  "aiEdit.accepted": "Change applied. The book is being rebuilt, this takes about a minute.",
  "aiEdit.rejected": "Change discarded. The book stays as it was.",
  "aiEdit.revert": "Undo the last AI edit",
  "aiEdit.reverted": "The last AI edit was undone. The book is being rebuilt.",
  "aiEdit.revertConfirm": "Undo the last AI edit and restore the previous text?",
  "aiEdit.history": "Previous edits",
  "aiEdit.status.running": "In progress",
  "aiEdit.status.preview": "Waiting for you",
  "aiEdit.status.accepted": "Applied",
  "aiEdit.status.rejected": "Discarded",
  "aiEdit.status.reverted": "Undone",
  "aiEdit.status.failed": "Not done (not counted)",
  "aiEdit.failedTitle": "The last edit could not be done and was not counted",
  "aiEdit.fail.gate": "The result would have damaged the book (footnotes, illustrations or formatting), so it was thrown away. Try a narrower instruction.",
  "aiEdit.fail.unchanged": "The AI found nothing to change for this instruction. Try wording it more specifically.",
  "aiEdit.fail.truncated": "This part is too long to edit in one go. Pick a single section.",
  "aiEdit.fail.chapter_changed": "This part of the book was edited after the preview was made, so the change no longer fits.",
  "aiEdit.fail.other": "Something went wrong on our side. Please try again.",
  "aiEdit.err.EDIT_ACTIVE": "Decide on the current change first.",
  "aiEdit.err.EDIT_LIMIT": "No AI edits left for this book.",
  "aiEdit.err.SCOPE_TOO_LARGE": "This part is too long for one edit. Pick a single section.",
  "aiEdit.err.PROMPT_TOO_SHORT": "Describe what should change.",
  "aiEdit.err.EDIT_RATE": "Too many edits in a short time. Try again in an hour.",
  "aiEdit.err.NOT_READY": "The book is being rebuilt. Try again in a moment.",
  "aiEdit.err.CHAPTER_CHANGED": "This part of the book changed in the meantime, so the change no longer fits.",
  "aiEdit.err.other": "Something went wrong. Please try again.",
};

export const pl: Record<string, string> = {
  "aiEdit.title": "Popraw z AI",
  "aiEdit.text":
    "Wskaż rozdział albo jego część i napisz, co zmienić: skrócić, uprościć, dodać przykład, zmienić ton. Najpierw zobaczysz wynik i zdecydujesz, czy go zostawić.",
  "aiEdit.left": "Pozostałe poprawki dla tej książki: {n} z {max}",
  "aiEdit.noneLeft": "Wykorzystano wszystkie {max} poprawki AI dla tej książki. W innych sprawach użyj „Sprawdź przez człowieka” poniżej albo popraw tekst samodzielnie w edytorze.",
  "aiEdit.scopeChapter": "Rozdział",
  "aiEdit.scopeSection": "Część rozdziału",
  "aiEdit.wholeChapter": "Cały rozdział",
  "aiEdit.chapterOption": "{n}. {title}",
  "aiEdit.tooLarge": "(za długie na jedną poprawkę, wybierz sekcję)",
  "aiEdit.promptLabel": "Co ma się zmienić?",
  "aiEdit.promptPlaceholder": "np. Skróć tę sekcję o jedną trzecią i zostaw listę kontrolną. Albo: wyjaśnij drugi akapit prostszymi słowami i dodaj krótki przykład z życia.",
  "aiEdit.start": "Pokaż zmianę",
  "aiEdit.unsaved": "Najpierw zapisz zmiany w edytorze. Poprawka AI pracuje na zapisanym tekście.",
  "aiEdit.running": "Poprawiam…",
  "aiEdit.runningText": "Zwykle trwa to od jednej do dwóch minut. Możesz opuścić tę stronę, podgląd będzie tu czekał.",
  "aiEdit.previewTitle": "Podgląd zmiany",
  "aiEdit.previewScope": "Zakres: {s}",
  "aiEdit.previewPrompt": "Twoje polecenie: {s}",
  "aiEdit.stats": "{before} → {after} słów",
  "aiEdit.statsFootnotes": "przypisy: {before} → {after}",
  "aiEdit.legendRemoved": "usunięte",
  "aiEdit.legendAdded": "nowe",
  "aiEdit.showUnchanged": "Pokaż niezmienione akapity",
  "aiEdit.hideUnchanged": "Ukryj niezmienione akapity",
  "aiEdit.unchangedCount": "{n} niezmienionych akapitów",
  "aiEdit.accept": "Zostaw tę zmianę",
  "aiEdit.reject": "Odrzuć",
  "aiEdit.accepted": "Zmiana wprowadzona. Książka składa się na nowo, potrwa to około minuty.",
  "aiEdit.rejected": "Zmiana odrzucona. Książka zostaje bez zmian.",
  "aiEdit.revert": "Cofnij ostatnią poprawkę AI",
  "aiEdit.reverted": "Ostatnia poprawka AI została cofnięta. Książka składa się na nowo.",
  "aiEdit.revertConfirm": "Cofnąć ostatnią poprawkę AI i przywrócić poprzedni tekst?",
  "aiEdit.history": "Wcześniejsze poprawki",
  "aiEdit.status.running": "W toku",
  "aiEdit.status.preview": "Czeka na Ciebie",
  "aiEdit.status.accepted": "Wprowadzona",
  "aiEdit.status.rejected": "Odrzucona",
  "aiEdit.status.reverted": "Cofnięta",
  "aiEdit.status.failed": "Niewykonana (nie liczy się)",
  "aiEdit.failedTitle": "Ostatniej poprawki nie udało się wykonać i nie została policzona",
  "aiEdit.fail.gate": "Wynik uszkodziłby książkę (przypisy, ilustracje albo formatowanie), więc został odrzucony. Spróbuj węższego polecenia.",
  "aiEdit.fail.unchanged": "AI nie znalazło nic do zmiany dla tego polecenia. Spróbuj sformułować je konkretniej.",
  "aiEdit.fail.truncated": "Ta część jest za długa na jedną poprawkę. Wybierz pojedynczą sekcję.",
  "aiEdit.fail.chapter_changed": "Ta część książki została zmieniona po przygotowaniu podglądu, więc poprawka już do niej nie pasuje.",
  "aiEdit.fail.other": "Coś poszło nie tak po naszej stronie. Spróbuj ponownie.",
  "aiEdit.err.EDIT_ACTIVE": "Najpierw zdecyduj o bieżącej zmianie.",
  "aiEdit.err.EDIT_LIMIT": "Nie ma już poprawek AI dla tej książki.",
  "aiEdit.err.SCOPE_TOO_LARGE": "Ta część jest za długa na jedną poprawkę. Wybierz pojedynczą sekcję.",
  "aiEdit.err.PROMPT_TOO_SHORT": "Opisz, co ma się zmienić.",
  "aiEdit.err.EDIT_RATE": "Za dużo poprawek w krótkim czasie. Spróbuj za godzinę.",
  "aiEdit.err.NOT_READY": "Książka składa się na nowo. Spróbuj za chwilę.",
  "aiEdit.err.CHAPTER_CHANGED": "Ta część książki zmieniła się w międzyczasie, więc poprawka już do niej nie pasuje.",
  "aiEdit.err.other": "Coś poszło nie tak. Spróbuj ponownie.",
};
