// i18n strings for: cover  (keys prefixed "cover.")
export const en: Record<string, string> = {
  "cover.heading": "Book Cover",
  "cover.subAiGenerated": "AI-generated cover",
  "cover.subCustomUploaded": "Custom uploaded cover",
  "cover.subNone": "No cover — click to add one",
  "cover.active": "Active",
  "cover.generate": "Generate",
  "cover.generateDesc": "AI-designed cover",
  "cover.upload": "Upload",
  "cover.uploadDesc": "Your own image",
  "cover.none": "None",
  "cover.noneDesc": "No cover page",
  "cover.layoutTemplate": "Layout Template",
  "cover.title": "Title",
  "cover.authorName": "Author Name",
  "cover.optional": "Optional",
  "cover.subtitle": "Subtitle",
  "cover.tagline": "Tagline",
  "cover.taglinePlaceholder": "e.g. 'A Practical Guide'",
  "cover.authorCredentials": "Author Credentials",
  "cover.authorCredentialsPlaceholder": "e.g. '15+ years in digital marketing'",
  "cover.featureBadgeText": "Feature Badge Text",
  "cover.featureBadgeTextPlaceholder": "e.g. '360°' or '2026'",
  "cover.featureBadgeSubtext": "Feature Badge Subtext",
  "cover.featureBadgeSubtextPlaceholder": "e.g. 'Complete Guide'",
  "cover.topicPillars": "Topic Pillars — up to 3 info boxes on cover",
  "cover.pillarTitle": "Title",
  "cover.pillarDescription": "Short description",
  "cover.addPillar": "+ Add pillar",
  "cover.generating": "Generating...",
  "cover.generateCover": "Generate Cover",
  "cover.regenerate": "Regenerate",
  "cover.remove": "Remove",
  "cover.preview": "Preview",
  "cover.openFullSize": "Open full size ↗",
  // toasts
  "cover.toastGenerated": "Cover generated!",
  "cover.toastGenerationFailed": "Generation failed",
  "cover.toastUploaded": "Custom cover uploaded!",
  "cover.toastUploadFailed": "Upload failed",
  "cover.toastRemoved": "Cover removed",
  "cover.toastRemoveFailed": "Failed to remove cover",
};

export const pl: Record<string, string> = {
  "cover.heading": "Okładka książki",
  "cover.subAiGenerated": "Okładka wygenerowana przez AI",
  "cover.subCustomUploaded": "Wgrana własna okładka",
  "cover.subNone": "Brak okładki — kliknij, aby dodać",
  "cover.active": "Aktywna",
  "cover.generate": "Wygeneruj",
  "cover.generateDesc": "Okładka zaprojektowana przez AI",
  "cover.upload": "Wgraj",
  "cover.uploadDesc": "Twój własny obraz",
  "cover.none": "Brak",
  "cover.noneDesc": "Bez strony okładki",
  "cover.layoutTemplate": "Szablon układu",
  "cover.title": "Tytuł",
  "cover.authorName": "Imię i nazwisko autora",
  "cover.optional": "Opcjonalnie",
  "cover.subtitle": "Podtytuł",
  "cover.tagline": "Hasło",
  "cover.taglinePlaceholder": "np. „Praktyczny przewodnik”",
  "cover.authorCredentials": "Kwalifikacje autora",
  "cover.authorCredentialsPlaceholder": "np. „15+ lat w marketingu cyfrowym”",
  "cover.featureBadgeText": "Tekst plakietki wyróżnienia",
  "cover.featureBadgeTextPlaceholder": "np. „360°” lub „2026”",
  "cover.featureBadgeSubtext": "Podtekst plakietki wyróżnienia",
  "cover.featureBadgeSubtextPlaceholder": "np. „Kompletny przewodnik”",
  "cover.topicPillars": "Filary tematyczne — do 3 ramek informacyjnych na okładce",
  "cover.pillarTitle": "Tytuł",
  "cover.pillarDescription": "Krótki opis",
  "cover.addPillar": "+ Dodaj filar",
  "cover.generating": "Generowanie...",
  "cover.generateCover": "Wygeneruj okładkę",
  "cover.regenerate": "Wygeneruj ponownie",
  "cover.remove": "Usuń",
  "cover.preview": "Podgląd",
  "cover.openFullSize": "Otwórz w pełnym rozmiarze ↗",
  // toasts
  "cover.toastGenerated": "Okładka wygenerowana!",
  "cover.toastGenerationFailed": "Generowanie nie powiodło się",
  "cover.toastUploaded": "Własna okładka wgrana!",
  "cover.toastUploadFailed": "Wgrywanie nie powiodło się",
  "cover.toastRemoved": "Okładka usunięta",
  "cover.toastRemoveFailed": "Nie udało się usunąć okładki",
};
