// i18n strings for: cover  (keys prefixed "cover.")
export const en: Record<string, string> = {
  "cover.heading": "Book Cover",
  "cover.subAiGenerated": "AI-generated cover",
  "cover.subCustomUploaded": "Custom uploaded cover",
  "cover.subNone": "No cover. Click to add one",
  "cover.active": "Active",
  "cover.generate": "Generate",
  "cover.generateDesc": "AI-designed cover",
  "cover.upload": "Upload",
  "cover.uploadDesc": "Your own image",
  "cover.none": "None",
  "cover.noneDesc": "No cover page",
  "cover.layoutTemplate": "Layout Template",
  "cover.title": "Title",
  "cover.authorName": "Author Name",
  "cover.optional": "Optional",
  "cover.subtitle": "Subtitle",
  "cover.tagline": "Tagline",
  "cover.taglinePlaceholder": "e.g. 'A Practical Guide'",
  "cover.authorCredentials": "Author Credentials",
  "cover.authorCredentialsPlaceholder": "e.g. '15+ years in digital marketing'",
  "cover.featureBadgeText": "Feature Badge Text",
  "cover.featureBadgeTextPlaceholder": "e.g. '360°' or '2026'",
  "cover.featureBadgeSubtext": "Feature Badge Subtext",
  "cover.featureBadgeSubtextPlaceholder": "e.g. 'Complete Guide'",
  "cover.topicPillars": "Topic Pillars (up to 3 info boxes on cover)",
  "cover.pillarTitle": "Title",
  "cover.pillarDescription": "Short description",
  "cover.addPillar": "+ Add pillar",
  "cover.generating": "Generating...",
  "cover.generateCover": "Generate Cover",
  "cover.regenerate": "Regenerate",
  "cover.remove": "Remove",
  "cover.preview": "Preview",
  "cover.openFullSize": "Open full size ↗",
  // toasts
  "cover.toastGenerated": "Cover generated!",
  "cover.toastGenerationFailed": "Generation failed",
  "cover.toastUploaded": "Custom cover uploaded!",
  "cover.toastUploadFailed": "Upload failed",
  "cover.toastRemoved": "Cover removed",
  "cover.toastRemoveFailed": "Failed to remove cover",
};

export const pl: Record<string, string> = {
  "cover.heading": "Okładka książki",
  "cover.subAiGenerated": "Okładka wygenerowana przez AI",
  "cover.subCustomUploaded": "Wgrana własna okładka",
  "cover.subNone": "Brak okładki. Kliknij, aby dodać",
  "cover.active": "Aktywna",
  "cover.generate": "Wygeneruj",
  "cover.generateDesc": "Okładka zaprojektowana przez AI",
  "cover.upload": "Wgraj",
  "cover.uploadDesc": "Twój własny obraz",
  "cover.none": "Brak",
  "cover.noneDesc": "Bez strony okładki",
  "cover.layoutTemplate": "Szablon układu",
  "cover.title": "Tytuł",
  "cover.authorName": "Imię i nazwisko autora",
  "cover.optional": "Opcjonalnie",
  "cover.subtitle": "Podtytuł",
  "cover.tagline": "Hasło",
  "cover.taglinePlaceholder": "np. „Praktyczny przewodnik”",
  "cover.authorCredentials": "Kwalifikacje autora",
  "cover.authorCredentialsPlaceholder": "np. „15+ lat w marketingu cyfrowym”",
  "cover.featureBadgeText": "Tekst plakietki wyróżnienia",
  "cover.featureBadgeTextPlaceholder": "np. „360°” lub „2026”",
  "cover.featureBadgeSubtext": "Podtekst plakietki wyróżnienia",
  "cover.featureBadgeSubtextPlaceholder": "np. „Kompletny przewodnik”",
  "cover.topicPillars": "Filary tematyczne (do 3 ramek informacyjnych na okładce)",
  "cover.pillarTitle": "Tytuł",
  "cover.pillarDescription": "Krótki opis",
  "cover.addPillar": "+ Dodaj filar",
  "cover.generating": "Generowanie...",
  "cover.generateCover": "Wygeneruj okładkę",
  "cover.regenerate": "Wygeneruj ponownie",
  "cover.remove": "Usuń",
  "cover.preview": "Podgląd",
  "cover.openFullSize": "Otwórz w pełnym rozmiarze ↗",
  // toasts
  "cover.toastGenerated": "Okładka wygenerowana!",
  "cover.toastGenerationFailed": "Generowanie nie powiodło się",
  "cover.toastUploaded": "Własna okładka wgrana!",
  "cover.toastUploadFailed": "Wgrywanie nie powiodło się",
  "cover.toastRemoved": "Okładka usunięta",
  "cover.toastRemoveFailed": "Nie udało się usunąć okładki",
};

export const de: Record<string, string> = {
  "cover.heading": "Buchcover",
  "cover.subAiGenerated": "KI-generiertes Cover",
  "cover.subCustomUploaded": "Eigenes Cover hochgeladen",
  "cover.subNone": "Kein Cover. Klicken Sie, um eines hinzuzufügen",
  "cover.active": "Aktiv",
  "cover.generate": "Generieren",
  "cover.generateDesc": "Von der KI gestaltetes Cover",
  "cover.upload": "Hochladen",
  "cover.uploadDesc": "Ihr eigenes Bild",
  "cover.none": "Ohne",
  "cover.noneDesc": "Keine Cover-Seite",
  "cover.layoutTemplate": "Layoutvorlage",
  "cover.title": "Titel",
  "cover.authorName": "Name des Autors",
  "cover.optional": "Optional",
  "cover.subtitle": "Untertitel",
  "cover.tagline": "Slogan",
  "cover.taglinePlaceholder": "z. B. „Ein Praxisleitfaden“",
  "cover.authorCredentials": "Qualifikation des Autors",
  "cover.authorCredentialsPlaceholder": "z. B. „Über 15 Jahre Erfahrung im digitalen Marketing“",
  "cover.featureBadgeText": "Text des Badges",
  "cover.featureBadgeTextPlaceholder": "z. B. „360°“ oder „2026“",
  "cover.featureBadgeSubtext": "Zusatztext des Badges",
  "cover.featureBadgeSubtextPlaceholder": "z. B. „Der komplette Leitfaden“",
  "cover.topicPillars": "Themensäulen (bis zu 3 Infokästen auf dem Cover)",
  "cover.pillarTitle": "Titel",
  "cover.pillarDescription": "Kurzbeschreibung",
  "cover.addPillar": "+ Säule hinzufügen",
  "cover.generating": "Wird generiert...",
  "cover.generateCover": "Cover generieren",
  "cover.regenerate": "Neu generieren",
  "cover.remove": "Entfernen",
  "cover.preview": "Vorschau",
  "cover.openFullSize": "In voller Größe öffnen ↗",
  // toasts
  "cover.toastGenerated": "Cover generiert!",
  "cover.toastGenerationFailed": "Generierung fehlgeschlagen",
  "cover.toastUploaded": "Eigenes Cover hochgeladen!",
  "cover.toastUploadFailed": "Hochladen fehlgeschlagen",
  "cover.toastRemoved": "Cover entfernt",
  "cover.toastRemoveFailed": "Cover konnte nicht entfernt werden",
};
