// i18n strings for: feedback  (keys prefixed "feedback.")
// Rating of a finished book + "Check by a human" correction requests.
export const en: Record<string, string> = {
  // rating
  "feedback.rateTitle": "How did your book turn out?",
  "feedback.rateText": "Your rating tells us what to improve. It takes a few seconds.",
  "feedback.yourRating": "Your rating",
  "feedback.starLabel": "{n} of 5 stars",
  "feedback.reasonsTitle": "What fell short? Pick all that apply",
  "feedback.reason.too_short": "Too short",
  "feedback.reason.repetitive": "Repetitions",
  "feedback.reason.factual": "Factual errors",
  "feedback.reason.style": "Style or language",
  "feedback.reason.sources": "Sources and footnotes",
  "feedback.reason.layout": "Layout and typesetting",
  "feedback.reason.cover": "Cover",
  "feedback.reason.images": "Illustrations",
  "feedback.commentPlaceholder": "Anything you would like to add? (optional)",
  "feedback.consent": "You may show my review on the InkMagnet website.",
  "feedback.consentName": "Sign it as (optional, e.g. first name and profession)",
  "feedback.send": "Send rating",
  "feedback.update": "Save changes",
  "feedback.change": "Change",
  "feedback.remove": "Remove",
  "feedback.cancel": "Cancel",
  "feedback.notNow": "Not now",
  "feedback.thanks": "Thank you for your rating!",
  "feedback.removed": "Rating removed",
  "feedback.error": "Something went wrong. Please try again.",
  "feedback.publishOn": "You agreed to show this review on our website.",
  // corrections
  "feedback.fixTitle": "Check by a human",
  "feedback.fixText":
    "Something not right? Describe what to fix and our editor will go through the book by hand. Free of charge.",
  "feedback.fixCta": "Request corrections",
  "feedback.fixScope": "Which part?",
  "feedback.fixWhole": "The whole book",
  "feedback.fixChapter": "Chapter {n}: {title}",
  "feedback.fixPlaceholder":
    "What should be corrected? The more specific, the better: page or section, what is wrong, what it should say.",
  "feedback.fixSend": "Send to the editor",
  "feedback.fixSent": "Sent. We will email you when the corrections are ready.",
  "feedback.fixTooShort": "Describe what to fix (at least 10 characters).",
  "feedback.fixLeft": "Requests used for this book: {used} of {max}",
  "feedback.fixOpenInfo": "Your request is with the editor. You can send another one once it is closed.",
  "feedback.fixLimitInfo": "You have used all {max} requests for this book. Write to contact@inkmagnet.com if something still needs fixing.",
  "feedback.fixHistory": "Your requests",
  "feedback.fixReply": "Editor's reply",
  "feedback.status.open": "Waiting",
  "feedback.status.in_progress": "In progress",
  "feedback.status.done": "Done",
  "feedback.status.rejected": "Closed",
};

export const pl: Record<string, string> = {
  "feedback.rateTitle": "Jak wyszła Twoja książka?",
  "feedback.rateText": "Twoja ocena mówi nam, co poprawić. Zajmie kilka sekund.",
  "feedback.yourRating": "Twoja ocena",
  "feedback.starLabel": "{n} z 5 gwiazdek",
  "feedback.reasonsTitle": "Czego zabrakło? Zaznacz wszystko, co pasuje",
  "feedback.reason.too_short": "Za krótka",
  "feedback.reason.repetitive": "Powtórzenia",
  "feedback.reason.factual": "Błędy merytoryczne",
  "feedback.reason.style": "Styl lub język",
  "feedback.reason.sources": "Źródła i przypisy",
  "feedback.reason.layout": "Skład i wygląd",
  "feedback.reason.cover": "Okładka",
  "feedback.reason.images": "Ilustracje",
  "feedback.commentPlaceholder": "Chcesz coś dodać? (opcjonalnie)",
  "feedback.consent": "Możecie pokazać moją opinię na stronie InkMagnet.",
  "feedback.consentName": "Podpis (opcjonalnie, np. imię i zawód)",
  "feedback.send": "Wyślij ocenę",
  "feedback.update": "Zapisz zmiany",
  "feedback.change": "Zmień",
  "feedback.remove": "Usuń",
  "feedback.cancel": "Anuluj",
  "feedback.notNow": "Nie teraz",
  "feedback.thanks": "Dziękujemy za ocenę!",
  "feedback.removed": "Ocena usunięta",
  "feedback.error": "Coś poszło nie tak. Spróbuj ponownie.",
  "feedback.publishOn": "Zgadzasz się na pokazanie tej opinii na naszej stronie.",
  "feedback.fixTitle": "Sprawdź przez człowieka",
  "feedback.fixText":
    "Coś się nie zgadza? Opisz, co poprawić, a nasz redaktor ręcznie przejrzy książkę. Bezpłatnie.",
  "feedback.fixCta": "Zgłoś poprawki",
  "feedback.fixScope": "Której części dotyczy?",
  "feedback.fixWhole": "Cała książka",
  "feedback.fixChapter": "Rozdział {n}: {title}",
  "feedback.fixPlaceholder":
    "Co poprawić? Im konkretniej, tym lepiej: strona lub sekcja, co jest nie tak, jak powinno być.",
  "feedback.fixSend": "Wyślij do redaktora",
  "feedback.fixSent": "Wysłane. Damy znać mailem, gdy poprawki będą gotowe.",
  "feedback.fixTooShort": "Opisz, co poprawić (co najmniej 10 znaków).",
  "feedback.fixLeft": "Wykorzystane zgłoszenia dla tej książki: {used} z {max}",
  "feedback.fixOpenInfo": "Twoje zgłoszenie jest u redaktora. Kolejne wyślesz, gdy to zostanie zamknięte.",
  "feedback.fixLimitInfo": "Wykorzystano wszystkie {max} zgłoszenia dla tej książki. Jeśli coś nadal wymaga poprawy, napisz na contact@inkmagnet.com.",
  "feedback.fixHistory": "Twoje zgłoszenia",
  "feedback.fixReply": "Odpowiedź redaktora",
  "feedback.status.open": "Czeka",
  "feedback.status.in_progress": "W toku",
  "feedback.status.done": "Zrobione",
  "feedback.status.rejected": "Zamknięte",
};

export const de: Record<string, string> = {
  // rating
  "feedback.rateTitle": "Wie ist Ihr Buch geworden?",
  "feedback.rateText": "Ihre Bewertung zeigt uns, was wir verbessern sollten. Es dauert nur ein paar Sekunden.",
  "feedback.yourRating": "Ihre Bewertung",
  "feedback.starLabel": "{n} von 5 Sternen",
  "feedback.reasonsTitle": "Was hat nicht überzeugt? Wählen Sie alles Zutreffende aus",
  "feedback.reason.too_short": "Zu kurz",
  "feedback.reason.repetitive": "Wiederholungen",
  "feedback.reason.factual": "Sachliche Fehler",
  "feedback.reason.style": "Stil oder Sprache",
  "feedback.reason.sources": "Quellen und Fußnoten",
  "feedback.reason.layout": "Layout und Satz",
  "feedback.reason.cover": "Cover",
  "feedback.reason.images": "Illustrationen",
  "feedback.commentPlaceholder": "Möchten Sie noch etwas ergänzen? (optional)",
  "feedback.consent": "Sie dürfen meine Bewertung auf der InkMagnet-Website zeigen.",
  "feedback.consentName": "Unterzeichnen als (optional, z. B. Vorname und Beruf)",
  "feedback.send": "Bewertung senden",
  "feedback.update": "Änderungen speichern",
  "feedback.change": "Ändern",
  "feedback.remove": "Entfernen",
  "feedback.cancel": "Abbrechen",
  "feedback.notNow": "Nicht jetzt",
  "feedback.thanks": "Vielen Dank für Ihre Bewertung!",
  "feedback.removed": "Bewertung entfernt",
  "feedback.error": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
  "feedback.publishOn": "Sie haben zugestimmt, dass diese Bewertung auf unserer Website gezeigt wird.",
  // corrections
  "feedback.fixTitle": "Von einem Menschen prüfen lassen",
  "feedback.fixText":
    "Etwas stimmt nicht? Beschreiben Sie, was korrigiert werden soll, und unser Lektor geht das Buch von Hand durch. Kostenlos.",
  "feedback.fixCta": "Korrekturen anfordern",
  "feedback.fixScope": "Welcher Teil?",
  "feedback.fixWhole": "Das ganze Buch",
  "feedback.fixChapter": "Kapitel {n}: {title}",
  "feedback.fixPlaceholder":
    "Was soll korrigiert werden? Je genauer, desto besser: Seite oder Abschnitt, was nicht stimmt, wie es richtig lauten soll.",
  "feedback.fixSend": "An den Lektor senden",
  "feedback.fixSent": "Gesendet. Wir benachrichtigen Sie per E-Mail, sobald die Korrekturen fertig sind.",
  "feedback.fixTooShort": "Beschreiben Sie, was korrigiert werden soll (mindestens 10 Zeichen).",
  "feedback.fixLeft": "Genutzte Korrekturanfragen für dieses Buch: {used} von {max}",
  "feedback.fixOpenInfo": "Ihre Korrekturanfrage liegt beim Lektor. Sobald sie abgeschlossen ist, können Sie eine weitere senden.",
  "feedback.fixLimitInfo": "Sie haben alle {max} Korrekturanfragen für dieses Buch genutzt. Schreiben Sie an contact@inkmagnet.com, falls noch etwas korrigiert werden muss.",
  "feedback.fixHistory": "Ihre Korrekturanfragen",
  "feedback.fixReply": "Antwort des Lektors",
  "feedback.status.open": "Wartet",
  "feedback.status.in_progress": "In Bearbeitung",
  "feedback.status.done": "Erledigt",
  "feedback.status.rejected": "Geschlossen",
};
