// i18n strings for: imageLibrary  (keys prefixed "imageLibrary.")
export const en: Record<string, string> = {
  "imageLibrary.title": "Insert Image",
  "imageLibrary.close": "Close",
  "imageLibrary.upload": "Upload Image",
  "imageLibrary.uploading": "Uploading...",
  "imageLibrary.formatsHint": "JPEG, PNG, WebP, GIF · Max 10 MB",
  "imageLibrary.noImages": "No images yet.",
  "imageLibrary.delete": "Delete",
  "imageLibrary.alignment": "Alignment",
  "imageLibrary.alignLeft": "Left",
  "imageLibrary.alignLeftDesc": "Text wraps on right",
  "imageLibrary.alignCenter": "Center",
  "imageLibrary.alignCenterDesc": "Between paragraphs",
  "imageLibrary.alignRight": "Right",
  "imageLibrary.alignRightDesc": "Text wraps on left",
  "imageLibrary.sizeLabel": "Size — {n}% of text width",
  "imageLibrary.sizeSmall": "Small",
  "imageLibrary.sizeMedium": "Medium",
  "imageLibrary.sizeLarge": "Large",
  "imageLibrary.sizeFull": "Full",
  "imageLibrary.layoutPreview": "Layout preview",
  "imageLibrary.captionLabel": "Caption (optional)",
  "imageLibrary.captionPlaceholder": "e.g., Figure 1: Market share comparison",
  "imageLibrary.selectImage": "Select an image",
  "imageLibrary.orUploadNew": "or upload a new one",
  "imageLibrary.cancel": "Cancel",
  "imageLibrary.insert": "Insert Image",
  // confirm
  "imageLibrary.confirmDelete": "Delete this image?",
  // toasts
  "imageLibrary.toastLoadFailed": "Failed to load images",
  "imageLibrary.toastMaxSize": "Max 10 MB",
  "imageLibrary.toastUploaded": "Image uploaded!",
  "imageLibrary.toastUploadFailed": "Upload failed",
  "imageLibrary.toastDeleted": "Deleted",
  "imageLibrary.toastDeleteFailed": "Delete failed",
};

export const pl: Record<string, string> = {
  "imageLibrary.title": "Wstaw obraz",
  "imageLibrary.close": "Zamknij",
  "imageLibrary.upload": "Prześlij obraz",
  "imageLibrary.uploading": "Przesyłanie...",
  "imageLibrary.formatsHint": "JPEG, PNG, WebP, GIF · maks. 10 MB",
  "imageLibrary.noImages": "Brak obrazów.",
  "imageLibrary.delete": "Usuń",
  "imageLibrary.alignment": "Wyrównanie",
  "imageLibrary.alignLeft": "Do lewej",
  "imageLibrary.alignLeftDesc": "Tekst opływa z prawej",
  "imageLibrary.alignCenter": "Wyśrodkuj",
  "imageLibrary.alignCenterDesc": "Między akapitami",
  "imageLibrary.alignRight": "Do prawej",
  "imageLibrary.alignRightDesc": "Tekst opływa z lewej",
  "imageLibrary.sizeLabel": "Rozmiar — {n}% szerokości tekstu",
  "imageLibrary.sizeSmall": "Mały",
  "imageLibrary.sizeMedium": "Średni",
  "imageLibrary.sizeLarge": "Duży",
  "imageLibrary.sizeFull": "Pełny",
  "imageLibrary.layoutPreview": "Podgląd układu",
  "imageLibrary.captionLabel": "Podpis (opcjonalnie)",
  "imageLibrary.captionPlaceholder": "np. Rysunek 1: Porównanie udziału w rynku",
  "imageLibrary.selectImage": "Wybierz obraz",
  "imageLibrary.orUploadNew": "lub prześlij nowy",
  "imageLibrary.cancel": "Anuluj",
  "imageLibrary.insert": "Wstaw obraz",
  // confirm
  "imageLibrary.confirmDelete": "Usunąć ten obraz?",
  // toasts
  "imageLibrary.toastLoadFailed": "Nie udało się wczytać obrazów",
  "imageLibrary.toastMaxSize": "Maks. 10 MB",
  "imageLibrary.toastUploaded": "Obraz przesłany!",
  "imageLibrary.toastUploadFailed": "Przesyłanie nie powiodło się",
  "imageLibrary.toastDeleted": "Usunięto",
  "imageLibrary.toastDeleteFailed": "Usuwanie nie powiodło się",
};
