// i18n strings for: sample  (free pre-payment style sample, keys "sample.")
export const en: Record<string, string> = {
  "sample.ctaTitle": "See what your book will look like",
  "sample.ctaText": "Two finished pages of chapter 1 in your chosen style and format, written and typeset like the final book. Free.",
  "sample.cta": "Show me a sample",
  "sample.runningTitle": "Writing and typesetting your sample…",
  "sample.runningText": "Usually 1–1.5 minutes. You can keep editing the outline meanwhile.",
  "sample.readyTitle": "Sample: the first two pages of your book",
  "sample.readyNote": "A style and layout sample. The final text is written after we research your topic, so it will be richer in facts and sources.",
  "sample.pageAlt": "Sample page {s}",
  "sample.tapToZoom": "Click a page to view it larger and zoom in.",
  "sample.zoomIn": "Zoom in",
  "sample.zoomOut": "Zoom out",
  "sample.close": "Close",
  "sample.prev": "Previous page",
  "sample.next": "Next page",
  "sample.failedRetry": "The sample didn't work out this time. You can try once more.",
  "sample.failedFinal": "The sample couldn't be prepared for this order. The book itself is not affected.",
  "sample.failed": "Couldn't start the sample. Please try again in a moment.",
  "sample.limit": "Today's free samples are used up. You can still order: after payment you review the full outline before writing starts.",
};

export const pl: Record<string, string> = {
  "sample.ctaTitle": "Zobacz, jak będzie wyglądać Twoja książka",
  "sample.ctaText": "Dwie gotowe strony rozdziału 1 w wybranym stylu i formacie, napisane i złożone jak finalna książka. Za darmo.",
  "sample.cta": "Pokaż próbkę",
  "sample.runningTitle": "Piszemy i składamy próbkę…",
  "sample.runningText": "Zwykle 1–1,5 minuty. W tym czasie możesz dalej poprawiać spis treści.",
  "sample.readyTitle": "Próbka: dwie pierwsze strony Twojej książki",
  "sample.readyNote": "To próbka stylu i składu. Ostateczny tekst powstaje po researchu tematu, więc będzie bogatszy w fakty i źródła.",
  "sample.pageAlt": "Strona próbki {s}",
  "sample.tapToZoom": "Kliknij stronę, żeby ją powiększyć i przybliżyć.",
  "sample.zoomIn": "Przybliż",
  "sample.zoomOut": "Oddal",
  "sample.close": "Zamknij",
  "sample.prev": "Poprzednia strona",
  "sample.next": "Następna strona",
  "sample.failedRetry": "Tym razem próbka się nie udała. Możesz spróbować jeszcze raz.",
  "sample.failedFinal": "Nie udało się przygotować próbki dla tego zamówienia. Nie ma to wpływu na samą książkę.",
  "sample.failed": "Nie udało się uruchomić próbki. Spróbuj za chwilę.",
  "sample.limit": "Dzisiejsze darmowe próbki są wykorzystane. Książkę nadal możesz zamówić: po płatności zobaczysz i poprawisz pełny konspekt, zanim zaczniemy pisać.",
};

export const de: Record<string, string> = {
  "sample.ctaTitle": "Sehen Sie, wie Ihr Buch aussehen wird",
  "sample.ctaText": "Zwei fertige Seiten aus Kapitel 1 im gewählten Stil und Format, geschrieben und gesetzt wie das fertige Buch. Kostenlos.",
  "sample.cta": "Leseprobe anzeigen",
  "sample.runningTitle": "Ihre Leseprobe wird geschrieben und gesetzt…",
  "sample.runningText": "In der Regel 1–1,5 Minuten. Sie können die Gliederung währenddessen weiter bearbeiten.",
  "sample.readyTitle": "Leseprobe: die ersten zwei Seiten Ihres Buches",
  "sample.readyNote": "Eine Probe für Stil und Layout. Der endgültige Text entsteht nach der Recherche zu Ihrem Thema und enthält daher mehr Fakten und Quellen.",
  "sample.pageAlt": "Leseprobe, Seite {s}",
  "sample.tapToZoom": "Klicken Sie auf eine Seite, um sie größer anzuzeigen und hineinzuzoomen.",
  "sample.zoomIn": "Vergrößern",
  "sample.zoomOut": "Verkleinern",
  "sample.close": "Schließen",
  "sample.prev": "Vorherige Seite",
  "sample.next": "Nächste Seite",
  "sample.failedRetry": "Die Leseprobe ist dieses Mal nicht gelungen. Sie können es noch einmal versuchen.",
  "sample.failedFinal": "Für diese Bestellung konnte keine Leseprobe erstellt werden. Das Buch selbst ist davon nicht betroffen.",
  "sample.failed": "Die Leseprobe konnte nicht gestartet werden. Bitte versuchen Sie es gleich noch einmal.",
  "sample.limit": "Die kostenlosen Leseproben für heute sind aufgebraucht. Bestellen können Sie trotzdem: Nach der Zahlung prüfen Sie die vollständige Gliederung, bevor das Schreiben beginnt.",
};
