// i18n strings for: sample  (free pre-payment style sample, keys "sample.")
export const en: Record<string, string> = {
  "sample.ctaTitle": "See what your book will look like",
  "sample.ctaText": "Two finished pages of chapter 1 in your chosen style and format — written and typeset like the final book. Free.",
  "sample.cta": "Show me a sample",
  "sample.runningTitle": "Writing and typesetting your sample…",
  "sample.runningText": "Usually 1–1.5 minutes. You can keep editing the outline meanwhile.",
  "sample.readyTitle": "Sample: the first two pages of your book",
  "sample.readyNote": "A style and layout sample. The final text is written after we research your topic, so it will be richer in facts and sources.",
  "sample.pageAlt": "Sample page {s}",
  "sample.tapToZoom": "Click a page to view it larger and zoom in.",
  "sample.zoomIn": "Zoom in",
  "sample.zoomOut": "Zoom out",
  "sample.close": "Close",
  "sample.prev": "Previous page",
  "sample.next": "Next page",
  "sample.failedRetry": "The sample didn't work out this time. You can try once more.",
  "sample.failedFinal": "The sample couldn't be prepared for this order. The book itself is not affected.",
  "sample.failed": "Couldn't start the sample. Please try again in a moment.",
  "sample.limit": "Today's free samples are used up. You can still order — after payment you review the full outline before writing starts.",
};

export const pl: Record<string, string> = {
  "sample.ctaTitle": "Zobacz, jak będzie wyglądać Twoja książka",
  "sample.ctaText": "Dwie gotowe strony rozdziału 1 w wybranym stylu i formacie — napisane i złożone jak finalna książka. Za darmo.",
  "sample.cta": "Pokaż próbkę",
  "sample.runningTitle": "Piszemy i składamy próbkę…",
  "sample.runningText": "Zwykle 1–1,5 minuty. W tym czasie możesz dalej poprawiać spis treści.",
  "sample.readyTitle": "Próbka: dwie pierwsze strony Twojej książki",
  "sample.readyNote": "To próbka stylu i składu. Ostateczny tekst powstaje po researchu tematu, więc będzie bogatszy w fakty i źródła.",
  "sample.pageAlt": "Strona próbki {s}",
  "sample.tapToZoom": "Kliknij stronę, żeby ją powiększyć i przybliżyć.",
  "sample.zoomIn": "Przybliż",
  "sample.zoomOut": "Oddal",
  "sample.close": "Zamknij",
  "sample.prev": "Poprzednia strona",
  "sample.next": "Następna strona",
  "sample.failedRetry": "Tym razem próbka się nie udała. Możesz spróbować jeszcze raz.",
  "sample.failedFinal": "Nie udało się przygotować próbki dla tego zamówienia. Nie ma to wpływu na samą książkę.",
  "sample.failed": "Nie udało się uruchomić próbki. Spróbuj za chwilę.",
  "sample.limit": "Dzisiejsze darmowe próbki są wykorzystane. Książkę nadal możesz zamówić — po płatności zobaczysz i poprawisz pełny konspekt, zanim zaczniemy pisać.",
};
