// i18n strings for: structure  (keys prefixed "structure.")
export const en: Record<string, string> = {
  "structure.bookStructure": "Book Structure",
  "structure.countLine": "{chapters} chapters • {pages} pages",
  "structure.removeChapter": "Remove chapter",
  "structure.removeSection": "Remove section",
  "structure.chapterLabel": "Ch. {s}",
  "structure.chapterCount": "{s} chapters",
  "structure.versionsIntro": "You have two versions of the outline. Pick the one you want. Your edits in each are kept.",
  "structure.versionFirst": "Version 1",
  "structure.versionRedo": "Version 2 (new)",
  "structure.bookTitle": "Book Title",
  "structure.addSection": "Add Section",
  "structure.addChapter": "Add Chapter",
  "structure.whatChanged": "What should be changed? (optional)",
  "structure.redoPlaceholder": "e.g., Add more practical examples, split chapter 2...",
  "structure.regenerate": "Regenerate",
  "structure.cancel": "Cancel",
  "structure.regenerateWithAi": "Regenerate structure with AI (one-time)",
  "structure.saveChanges": "Save Changes",
  "structure.saving": "Saving...",
  "structure.approveContinue": "Approve & Continue",
  "structure.savedToast": "Structure saved!",
  "structure.saveFailed": "Save failed",
  "structure.needChapter": "Need at least 1 chapter",
  "structure.needSection": "Need at least 1 section",
  "structure.regenerating": "Regenerating structure...",
  "structure.redoFailed": "Redo failed",
  "structure.newChapter": "New Chapter",
  "structure.chapterDescription": "Chapter description",
  "structure.newSection": "New Section",
  "structure.sectionDescription": "Section description",
};
export const pl: Record<string, string> = {
  "structure.bookStructure": "Struktura książki",
  "structure.countLine": "{chapters} rozdz. • {pages} stron",
  "structure.removeChapter": "Usuń rozdział",
  "structure.removeSection": "Usuń podrozdział",
  "structure.chapterLabel": "Rozdz. {s}",
  "structure.chapterCount": "rozdziały: {s}",
  "structure.versionsIntro": "Masz dwie wersje spisu treści. Wybierz tę, którą chcesz. Twoje poprawki w każdej zostają zapisane.",
  "structure.versionFirst": "Wersja 1",
  "structure.versionRedo": "Wersja 2 (nowa)",
  "structure.bookTitle": "Tytuł książki",
  "structure.addSection": "Dodaj podrozdział",
  "structure.addChapter": "Dodaj rozdział",
  "structure.whatChanged": "Co należy zmienić? (opcjonalnie)",
  "structure.redoPlaceholder": "np. Dodaj więcej praktycznych przykładów, podziel rozdział 2...",
  "structure.regenerate": "Wygeneruj ponownie",
  "structure.cancel": "Anuluj",
  "structure.regenerateWithAi": "Wygeneruj strukturę ponownie z AI (jednorazowo)",
  "structure.saveChanges": "Zapisz zmiany",
  "structure.saving": "Zapisywanie...",
  "structure.approveContinue": "Zatwierdź i kontynuuj",
  "structure.savedToast": "Struktura zapisana!",
  "structure.saveFailed": "Zapisywanie nie powiodło się",
  "structure.needChapter": "Potrzebny co najmniej 1 rozdział",
  "structure.needSection": "Potrzebny co najmniej 1 podrozdział",
  "structure.regenerating": "Generowanie struktury...",
  "structure.redoFailed": "Ponowne generowanie nie powiodło się",
  "structure.newChapter": "Nowy rozdział",
  "structure.chapterDescription": "Opis rozdziału",
  "structure.newSection": "Nowy podrozdział",
  "structure.sectionDescription": "Opis podrozdziału",
};
export const de: Record<string, string> = {
  "structure.bookStructure": "Gliederung des Buches",
  "structure.countLine": "{chapters} Kapitel • {pages} Seiten",
  "structure.removeChapter": "Kapitel entfernen",
  "structure.removeSection": "Abschnitt entfernen",
  "structure.chapterLabel": "Kap. {s}",
  "structure.chapterCount": "{s} Kapitel",
  "structure.versionsIntro": "Sie haben zwei Versionen der Gliederung. Wählen Sie die gewünschte aus. Ihre Änderungen bleiben in beiden erhalten.",
  "structure.versionFirst": "Version 1",
  "structure.versionRedo": "Version 2 (neu)",
  "structure.bookTitle": "Buchtitel",
  "structure.addSection": "Abschnitt hinzufügen",
  "structure.addChapter": "Kapitel hinzufügen",
  "structure.whatChanged": "Was soll geändert werden? (optional)",
  "structure.redoPlaceholder": "z. B. Mehr Praxisbeispiele ergänzen, Kapitel 2 aufteilen...",
  "structure.regenerate": "Neu erstellen",
  "structure.cancel": "Abbrechen",
  "structure.regenerateWithAi": "Gliederung mit KI neu erstellen (einmalig)",
  "structure.saveChanges": "Änderungen speichern",
  "structure.saving": "Wird gespeichert...",
  "structure.approveContinue": "Freigeben und fortfahren",
  "structure.savedToast": "Gliederung gespeichert!",
  "structure.saveFailed": "Speichern fehlgeschlagen",
  "structure.needChapter": "Mindestens 1 Kapitel erforderlich",
  "structure.needSection": "Mindestens 1 Abschnitt erforderlich",
  "structure.regenerating": "Gliederung wird neu erstellt...",
  "structure.redoFailed": "Neuerstellung fehlgeschlagen",
  "structure.newChapter": "Neues Kapitel",
  "structure.chapterDescription": "Kapitelbeschreibung",
  "structure.newSection": "Neuer Abschnitt",
  "structure.sectionDescription": "Abschnittsbeschreibung",
};
