// i18n strings for: structure  (keys prefixed "structure.")
export const en: Record<string, string> = {
  "structure.bookStructure": "Book Structure",
  "structure.countLine": "{chapters} chapters • {pages} pages",
  "structure.bookTitle": "Book Title",
  "structure.addSection": "Add Section",
  "structure.addChapter": "Add Chapter",
  "structure.whatChanged": "What should be changed? (optional)",
  "structure.redoPlaceholder": "e.g., Add more practical examples, split chapter 2...",
  "structure.regenerate": "Regenerate",
  "structure.cancel": "Cancel",
  "structure.regenerateWithAi": "Regenerate structure with AI (one-time)",
  "structure.saveChanges": "Save Changes",
  "structure.saving": "Saving...",
  "structure.approveContinue": "Approve & Continue",
  "structure.savedToast": "Structure saved!",
  "structure.saveFailed": "Save failed",
  "structure.needChapter": "Need at least 1 chapter",
  "structure.needSection": "Need at least 1 section",
  "structure.regenerating": "Regenerating structure...",
  "structure.redoFailed": "Redo failed",
  "structure.newChapter": "New Chapter",
  "structure.chapterDescription": "Chapter description",
  "structure.newSection": "New Section",
  "structure.sectionDescription": "Section description",
};
export const pl: Record<string, string> = {
  "structure.bookStructure": "Struktura książki",
  "structure.countLine": "{chapters} rozdz. • {pages} stron",
  "structure.bookTitle": "Tytuł książki",
  "structure.addSection": "Dodaj podrozdział",
  "structure.addChapter": "Dodaj rozdział",
  "structure.whatChanged": "Co należy zmienić? (opcjonalnie)",
  "structure.redoPlaceholder": "np. Dodaj więcej praktycznych przykładów, podziel rozdział 2...",
  "structure.regenerate": "Wygeneruj ponownie",
  "structure.cancel": "Anuluj",
  "structure.regenerateWithAi": "Wygeneruj strukturę ponownie z AI (jednorazowo)",
  "structure.saveChanges": "Zapisz zmiany",
  "structure.saving": "Zapisywanie...",
  "structure.approveContinue": "Zatwierdź i kontynuuj",
  "structure.savedToast": "Struktura zapisana!",
  "structure.saveFailed": "Zapisywanie nie powiodło się",
  "structure.needChapter": "Potrzebny co najmniej 1 rozdział",
  "structure.needSection": "Potrzebny co najmniej 1 podrozdział",
  "structure.regenerating": "Generowanie struktury...",
  "structure.redoFailed": "Ponowne generowanie nie powiodło się",
  "structure.newChapter": "Nowy rozdział",
  "structure.chapterDescription": "Opis rozdziału",
  "structure.newSection": "Nowy podrozdział",
  "structure.sectionDescription": "Opis podrozdziału",
};
