// i18n strings for: titlePage  (keys prefixed "titlePage.")
export const en: Record<string, string> = {
  // ── TitlePageEditor ──
  "titlePage.heading": "Title Page",
  "titlePage.bookTitle": "Book Title",
  "titlePage.bookTitlePlaceholder": "Your Book Title",
  "titlePage.author": "Author",
  "titlePage.optional": "optional",
  "titlePage.authorPlaceholder": "John Smith",
  "titlePage.subtitle": "Subtitle",
  "titlePage.recompileHint": "Changes will appear after PDF recompilation",
  "titlePage.saving": "Saving...",
  "titlePage.saved": "Saved",
  "titlePage.save": "Save",
  "titlePage.toastTitleRequired": "Title is required",
  "titlePage.toastUpdated": "Title page updated",
  "titlePage.toastSaveFailed": "Save failed",
  // ── ColophonEditor ──
  "titlePage.colophonHeading": "Copyright Page",
  "titlePage.enabled": "Enabled",
  "titlePage.disabled": "Disabled",
  "titlePage.insertTemplate": "Insert template",
  "titlePage.content": "Content",
  "titlePage.colophonPlaceholder": "Type copyright page content or click 'Insert template'...",
  "titlePage.lineHint": "Each line = new line in book. Empty line = spacing.",
  "titlePage.preview": "Preview",
  "titlePage.colophonPreview": "Copyright page preview",
  "titlePage.colophonRecompileHint": "Appears after the title page upon recompilation",
  "titlePage.defaultAuthor": "Author",
  "titlePage.toastColophonSaved": "Copyright page saved",
};

export const pl: Record<string, string> = {
  // ── TitlePageEditor ──
  "titlePage.heading": "Strona tytułowa",
  "titlePage.bookTitle": "Tytuł książki",
  "titlePage.bookTitlePlaceholder": "Tytuł Twojej książki",
  "titlePage.author": "Autor",
  "titlePage.optional": "opcjonalnie",
  "titlePage.authorPlaceholder": "Jan Kowalski",
  "titlePage.subtitle": "Podtytuł",
  "titlePage.recompileHint": "Zmiany pojawią się po rekompilacji PDF",
  "titlePage.saving": "Zapisywanie...",
  "titlePage.saved": "Zapisano",
  "titlePage.save": "Zapisz",
  "titlePage.toastTitleRequired": "Tytuł jest wymagany",
  "titlePage.toastUpdated": "Strona tytułowa zaktualizowana",
  "titlePage.toastSaveFailed": "Zapis nie powiódł się",
  // ── ColophonEditor ──
  "titlePage.colophonHeading": "Strona redakcyjna",
  "titlePage.enabled": "Włączona",
  "titlePage.disabled": "Wyłączona",
  "titlePage.insertTemplate": "Wstaw szablon",
  "titlePage.content": "Treść",
  "titlePage.colophonPlaceholder": "Wpisz treść strony redakcyjnej lub kliknij „Wstaw szablon”...",
  "titlePage.lineHint": "Każda linia = nowa linia w książce. Pusta linia = odstęp.",
  "titlePage.preview": "Podgląd",
  "titlePage.colophonPreview": "Podgląd strony redakcyjnej",
  "titlePage.colophonRecompileHint": "Pojawi się po stronie tytułowej po rekompilacji",
  "titlePage.defaultAuthor": "Autor",
  "titlePage.toastColophonSaved": "Strona redakcyjna zapisana",
};
