// i18n strings for: titlePage  (keys prefixed "titlePage.")
export const en: Record<string, string> = {
  // ── TitlePageEditor ──
  "titlePage.heading": "Title Page",
  "titlePage.bookTitle": "Book Title",
  "titlePage.bookTitlePlaceholder": "Your Book Title",
  "titlePage.author": "Author",
  "titlePage.optional": "optional",
  "titlePage.authorPlaceholder": "John Smith",
  "titlePage.subtitle": "Subtitle",
  "titlePage.recompileHint": "Changes will appear after PDF recompilation",
  "titlePage.saving": "Saving...",
  "titlePage.saved": "Saved",
  "titlePage.save": "Save",
  "titlePage.toastTitleRequired": "Title is required",
  "titlePage.toastUpdated": "Title page updated",
  "titlePage.toastSaveFailed": "Save failed",
  // ── ColophonEditor ──
  "titlePage.colophonHeading": "Copyright Page",
  "titlePage.enabled": "Enabled",
  "titlePage.disabled": "Disabled",
  "titlePage.insertTemplate": "Insert template",
  "titlePage.content": "Content",
  "titlePage.colophonPlaceholder": "Type copyright page content or click 'Insert template'...",
  "titlePage.lineHint": "Each line = new line in book. Empty line = spacing.",
  "titlePage.preview": "Preview",
  "titlePage.colophonPreview": "Copyright page preview",
  "titlePage.colophonRecompileHint": "Appears after the title page upon recompilation",
  // ── NumberingSettings ──
  "titlePage.numberingHeading": "Heading numbering",
  "titlePage.numberingIntro": "How chapters, sections and items are numbered. \"Auto\" follows the author brief's decision for this book; pick another scheme to override it.",
  "titlePage.numberingSave": "Save",
  "titlePage.numberingSaved": "Numbering saved — recompile to apply",
  "titlePage.numberingSaveFailed": "Could not save numbering",
  "titlePage.numberingAuto": "Auto",
  "titlePage.numbering_auto_desc": "Decided by the author brief from the book's genre.",
  "titlePage.numbering_hierarchical": "Hierarchical",
  "titlePage.numbering_hierarchical_desc": "1. / 1.1. / 1.1.1. — textbooks, technical guides, anything cross-referenced by number.",
  "titlePage.numbering_chapters": "Chapters only",
  "titlePage.numbering_chapters_desc": "Numbered chapters, unnumbered sections — most practical handbooks.",
  "titlePage.numbering_none": "No numbers",
  "titlePage.numbering_none_desc": "Nothing is numbered — essays, narrative books, short lead magnets.",
  "titlePage.numbering_items": "Numbered items",
  "titlePage.numbering_items_desc": "One continuous counter across the book: Recipe 52, Project 7, Exercise 14 — for collections.",
  "titlePage.numberingItemLabel": "Item label",
  "titlePage.numberingItemDefault": "Item",
  "titlePage.numberingItemHint": "printed before the number, e.g. Recipe 52",
  "titlePage.numberingFromBrief": "Current scheme chosen by the author brief",
  "titlePage.numberingFromProject": "Current scheme set by you",
  "titlePage.numberingFromDefault": "Current scheme: platform default",
  "titlePage.defaultAuthor": "Author",
  "titlePage.toastColophonSaved": "Copyright page saved",
};

export const pl: Record<string, string> = {
  // ── TitlePageEditor ──
  "titlePage.heading": "Strona tytułowa",
  "titlePage.bookTitle": "Tytuł książki",
  "titlePage.bookTitlePlaceholder": "Tytuł Twojej książki",
  "titlePage.author": "Autor",
  "titlePage.optional": "opcjonalnie",
  "titlePage.authorPlaceholder": "Jan Kowalski",
  "titlePage.subtitle": "Podtytuł",
  "titlePage.recompileHint": "Zmiany pojawią się po rekompilacji PDF",
  "titlePage.saving": "Zapisywanie...",
  "titlePage.saved": "Zapisano",
  "titlePage.save": "Zapisz",
  "titlePage.toastTitleRequired": "Tytuł jest wymagany",
  "titlePage.toastUpdated": "Strona tytułowa zaktualizowana",
  "titlePage.toastSaveFailed": "Zapis nie powiódł się",
  // ── ColophonEditor ──
  "titlePage.colophonHeading": "Strona redakcyjna",
  "titlePage.enabled": "Włączona",
  "titlePage.disabled": "Wyłączona",
  "titlePage.insertTemplate": "Wstaw szablon",
  "titlePage.content": "Treść",
  "titlePage.colophonPlaceholder": "Wpisz treść strony redakcyjnej lub kliknij „Wstaw szablon”...",
  "titlePage.lineHint": "Każda linia = nowa linia w książce. Pusta linia = odstęp.",
  "titlePage.preview": "Podgląd",
  "titlePage.colophonPreview": "Podgląd strony redakcyjnej",
  "titlePage.colophonRecompileHint": "Pojawi się po stronie tytułowej po rekompilacji",
  // ── NumberingSettings ──
  "titlePage.numberingHeading": "Numeracja nagłówków",
  "titlePage.numberingIntro": "Jak numerowane są rozdziały, sekcje i pozycje. „Auto” podąża za decyzją briefu autorskiego dla tej książki; wybierz inny schemat, żeby ją nadpisać.",
  "titlePage.numberingSave": "Zapisz",
  "titlePage.numberingSaved": "Numeracja zapisana — złóż książkę ponownie, żeby ją zastosować",
  "titlePage.numberingSaveFailed": "Nie udało się zapisać numeracji",
  "titlePage.numberingAuto": "Auto",
  "titlePage.numbering_auto_desc": "Decyduje brief autorski na podstawie gatunku książki.",
  "titlePage.numbering_hierarchical": "Hierarchiczna",
  "titlePage.numbering_hierarchical_desc": "1. / 1.1. / 1.1.1. — podręczniki, poradniki techniczne, wszystko, do czego czytelnik odsyła po numerze.",
  "titlePage.numbering_chapters": "Tylko rozdziały",
  "titlePage.numbering_chapters_desc": "Numerowane rozdziały, sekcje bez numerów — większość poradników.",
  "titlePage.numbering_none": "Bez numerów",
  "titlePage.numbering_none_desc": "Nic nie jest numerowane — eseje, książki narracyjne, krótkie lead magnety.",
  "titlePage.numbering_items": "Numerowane pozycje",
  "titlePage.numbering_items_desc": "Jeden ciągły licznik przez całą książkę: Przepis 52, Projekt 7, Ćwiczenie 14 — dla książek-kolekcji.",
  "titlePage.numberingItemLabel": "Etykieta pozycji",
  "titlePage.numberingItemDefault": "Pozycja",
  "titlePage.numberingItemHint": "drukowana przed numerem, np. Przepis 52",
  "titlePage.numberingFromBrief": "Obecny schemat wybrał brief autorski",
  "titlePage.numberingFromProject": "Obecny schemat ustawiony przez Ciebie",
  "titlePage.numberingFromDefault": "Obecny schemat: domyślny platformy",
  "titlePage.defaultAuthor": "Autor",
  "titlePage.toastColophonSaved": "Strona redakcyjna zapisana",
};
